In [73]:
import re
with open("./data/input.txt") as f:
    alma = f.read()

alma = alma.split("\n\n")
seeds = alma.pop(0)
    

In [74]:
def convert_vals_to_ints(maps):
   return [[int(m) for m in map.split()] for map in maps]

def get_mapping(line):
    map = re.match(r"[a-z\-]+", line).group(0)
    vals = re.findall(r"\n(\d+\s+\d+\s+\d+)", line)
    return map, convert_vals_to_ints(vals)


def return_target(to_be_mapped, map):
    for row in map:
        destination, source, range = tuple(row)
        if (to_be_mapped >= source) and (to_be_mapped < (source + range)):
            return destination + (to_be_mapped-source)
    return to_be_mapped

In [75]:
seeds = [int(seed) for seed in seeds.split(":")[1].split()]

In [76]:
all_the_maps = {}
for row in alma:
    map, vals = get_mapping(row)
    all_the_maps[map]=vals


In [77]:
def map_seed_to_end(seed):
    for key, val in all_the_maps.items():
        # print(f"{key:25}:  seed in {seed}: seed out {return_target(seed, val)}")
        seed = return_target(seed, val)
    
    return seed

min([map_seed_to_end(seed) for seed in seeds])


486613012

486613012 is correct!

In [78]:
# # part 2 
# import math
# seed_start = 2906961955
# seed_range = 52237479
# ans = math.inf
# for i in range(seed_start, seed_start+seed_range):
#     ans = min(map_seed_to_end(i), ans)

In [79]:
import numpy as np

print(seeds)

seed_array = np.array(seeds).reshape(-1, 2)
seed_array[:, 1] = seed_array[:, 1] + seed_array[:, 0]
seed_array.sort(0)
seed_array






[2906961955, 52237479, 1600322402, 372221628, 2347782594, 164705568, 541904540, 89745770, 126821306, 192539923, 3411274151, 496169308, 919015581, 8667739, 654599767, 160781040, 3945616935, 85197451, 999146581, 344584779]


array([[ 126821306,  319361229],
       [ 541904540,  631650310],
       [ 654599767,  815380807],
       [ 919015581,  927683320],
       [ 999146581, 1343731360],
       [1600322402, 1972544030],
       [2347782594, 2512488162],
       [2906961955, 2959199434],
       [3411274151, 3907443459],
       [3945616935, 4030814386]])

In [80]:
# Convert to 2D array
seeds_2d = [tuple(seeds[i:i + 2]) for i in range(0, len(seeds), 2)]
seeds_2d


[(2906961955, 52237479),
 (1600322402, 372221628),
 (2347782594, 164705568),
 (541904540, 89745770),
 (126821306, 192539923),
 (3411274151, 496169308),
 (919015581, 8667739),
 (654599767, 160781040),
 (3945616935, 85197451),
 (999146581, 344584779)]

In [82]:
import concurrent.futures
import math

def find_min_seed_for_range(seed_start, seed_range):
    ans = math.inf
    for i in range(seed_start, seed_start + seed_range):
        ans = min(map_seed_to_end(i), ans)  # Assuming map_seed_to_end function is defined
    return ans


future_results = []
with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
    # Submit the function to run asynchronously on each argument
    future_results = [executor.submit(find_min_seed_for_range, *arg) for arg in seeds_2d]

    # Gather the results as they're completed
    final_results = []
    for future in concurrent.futures.as_completed(future_results):
        final_results.append(future.result())

print(final_results)



[4225564962, 127158107, 239072070, 1254705509, 1312864011, 374323335, 942540950, 197937586, 70478641, 56931769]


In [83]:
min(final_results)

56931769

In [85]:
# compute backwards from the lowest number
# destination, source, range

# some kind of search 





In [86]:
def chunk_range(start_seed, end_seed, step_size):
    chunk = [i for i in range(start_seed, end_seed, step_size)]
    chunk.append(end_seed)
    return chunk

def chunk_search_min(start_range, end_range, INT):
    # INT = 1_000_000
    while INT > 0: 
        input_seeds = chunk_range(start_range, end_range, INT)
        # print(input_seeds)
        output_seeds = [map_seed_to_end(interval) for interval in input_seeds]
        # print(f"Checked interval:\t {start_range:9,} - {end_range:9,} | Interval size {(end_range-start_range):,} | Number Steps {len(input_seeds)}")
        
        min_index = output_seeds.index(min(output_seeds))
        min_interval = input_seeds[min_index]

        # print(f"Min index {min_index}: Min Input {min_interval:9,}")
        start_range = min_interval-INT
        end_range = min_interval+INT
        INT = INT//10 

    return output_seeds[min_index]

import numpy as np
seed_array = np.array(seeds).reshape(-1, 2)

print(seed_array)
seed_array[:, 1] = seed_array[:, 1] + seed_array[:, 0]
seed_array.sort(0)

print(seed_array)

for s in seed_array:
    if s[0] <= 3876934459 <= s[1]:
        print(s)


chunk_search_min(3876134459, 3876934459, 10)

[[2906961955   52237479]
 [1600322402  372221628]
 [2347782594  164705568]
 [ 541904540   89745770]
 [ 126821306  192539923]
 [3411274151  496169308]
 [ 919015581    8667739]
 [ 654599767  160781040]
 [3945616935   85197451]
 [ 999146581  344584779]]
[[ 126821306  319361229]
 [ 541904540  631650310]
 [ 654599767  815380807]
 [ 919015581  927683320]
 [ 999146581 1343731360]
 [1600322402 1972544030]
 [2347782594 2512488162]
 [2906961955 2959199434]
 [3411274151 3907443459]
 [3945616935 4030814386]]
[3411274151 3907443459]


TypeError: 'int' object is not callable

In [87]:
def chunk_range(start_seed, end_seed, step_size):
    chunk = [i for i in range(start_seed, end_seed, step_size)]
    chunk.append(end_seed)
    return chunk

In [88]:
chunk_range(1, 100, 1)

TypeError: 'int' object is not callable